version: '3.7'
services:
  nginx:
    depends_on:
      - frontend
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx/local
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/artifacts:/app/server/artifacts:rw
    ports:
     - "8000:8000"
