export const GET_TWEETS = 'GET_TWEETS'
export const GET_TRENDING = 'GET_TRENDING'
export const TWEETS_LOADING = 'TWEETS_LOADING'
export const TRENDS_LOADING = 'TRENDS_LOADING'
export const FILTER_POS = 'FILTER_POS'
export const FILTER_NEG = 'FILTER_NEG'
export const FILTER_NUE = 'FILTER_NUE'
export const FILTER_CLEAR = 'FILTER_CLEAR'
